name: penalty-env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Remove or adjust if you're using CPU
  - pip
  - pip:
      - pytorchvideo
      - opencv-python
      - mediapipe
      - shap
      - scikit-learn
      - matplotlib
      - pandas
